# name: Super-Linter

# on:
#   push:
#   schedule:
#     - cron: "0 0 * * *"  # Runs at 00:00 (midnight) UTC every day

# jobs:
#   test:
#     name: Run Tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2  # Checkout the repository code

#       - name: 23f1002560@ds.study.iitm.ac.in
#         run: |
#           echo "Hello, from email!" > hello.txt  # Example change

#       - name: Commit changes
#         env:
#             GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
#           git add .
#           git commit -m "Automated commit from GitHub Actions"
#           git push https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
name: Super-Linter

on:
  push:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 (midnight) UTC every day

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Make changes
        run: |
          echo "Hello, world!" > hello.txt  # Example change

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
