name: Super-Linter

on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: 23f1002560@ds.study.iitm.ac.in
        run: echo "Hello, world!"  # A simple echo statement




 
